from selenium.webdriver.common.by import By

class ProductLocators:
    SHOP_BUTTON = (By.XPATH, '//*[@id="modal-1-content"]/ul/ul/li/a[contains(text(), "Shop")]')
    SHOP_PRODUCT_TEXT = (By.XPATH, '//*[@id="wp--skip-link--target"]/h1')
    PRODUCTS_NAME = (By.XPATH, "//a[@data-wc-on--click='woocommerce/product-collection::actions.viewProduct' and text()='Demo Product']")
    PRODUCTS_PRICE = (By.XPATH, "//bdi[contains(text(), '10') and ./span[@class='woocommerce-Price-currencySymbol']]")
    ADD_TO_CART_BUTTON = (By.XPATH, '//*[@id="wp--skip-link--target"]/div[4]/ul/li/div/button')
    CART_ICON = (By.CSS_SELECTOR, "button.wc-block-mini-cart__button")
    PRODUCT_NAME = (By.XPATH, '//a[@class="wc-block-components-product-name"]')
    PRODUCT_QUANTITY = (By.CSS_SELECTOR, 'input.wc-block-components-quantity-selector__input')
    PRODUCT_PRICE = (By.CSS_SELECTOR, 'span.wc-block-formatted-money-amount.wc-block-components-formatted-money-amount.wc-block-components-product-price__value')
    CHECKOUT_BUTTON = (By.CSS_SELECTOR, 'a.wc-block-components-button.wc-block-mini-cart__footer-checkout')
    CHECKOUT_PAGE_TEXT = (By.XPATH, '/html/body/div[1]/header/div/p/a')
    BILLING_FIRST_NAME = (By.ID, "billing_first_name")
    BILLING_LAST_NAME = (By.ID, "billing_last_name")
    BILLING_COUNTRY = (By.ID, "billing_country")
    BILLING_ADDRESS_1 = (By.ID, "billing_address_1")
    BILLING_CITY = (By.ID, "billing_city")
    BILLING_POSTCODE = (By.ID, "billing_postcode")
    BILLING_PHONE = (By.ID, "billing_phone")
    BILLING_EMAIL = (By.ID, "billing_email")
    Order_PRODUCT_NAME = (By.XPATH, '//*[@id="order_review"]/table/tbody/tr/td[1][contains(text(), "Demo Product")]')
    SUBTOTAL = (By.XPATH, '//table/tbody/tr[1]/td[2]')
    SHIPPING = (By.XPATH, '//table/tfoot/tr[2]/td')
    TOTAL = (By.XPATH, '//table/tfoot/tr[3]/td')
    PAYMENT_METHODS = (By.CSS_SELECTOR,'#payment ul.payment_methods > li > label')
    PAYARC_PAYMENT_METHOD = (By.ID, 'payment_method_payarc_hosted')
    PLACE_ORDER_BUTTON = (By.ID, "place_order")
    PLACE_ORDERS_BUTTON = (By.ID, "place_order")
    PAYMENT_IFRAME = (By.CLASS_NAME, "payarc-js-sdk-modal-layer__iframe")
    CARD_NUMBER_FIELD = (By.CSS_SELECTOR, "#cardpan.UiTextField_input_2FIbZ")
    EXPIRATION_DATE_FIELD = (By.XPATH, '//*[@id="p-Card"]/div/div[3]/div[1]/input')
    CVC_CVV_FIELD = (By.XPATH, '//*[@id="p-Card"]/div/div[3]/div[2]/div[1]/input')
    FIRST_NAME_FIELD = (By.CSS_SELECTOR, "input[name='First Name']")
    LAST_NAME_FIELD = (By.CSS_SELECTOR, "input[name='Last Name']")
    ADDRESS_LINE1_FIELD = (By.CSS_SELECTOR, "input[name='Address Line 1'].UiTextField_input_2FIbZ")
    ADDRESS_LINE2_FIELD = (By.CSS_SELECTOR, "input[name='Address Line 2']")
    CITY_FIELD = (By.CSS_SELECTOR, "input[tabindex='8']")
    Status_FIELD = (By.XPATH, '//*[@id="p-Card"]/div/div[6]/div[3]/div[2]/div/div[1]')
    STATE_DROPDOWN = (By.XPATH, "//*[text()='{}']")
    STATE_OPTION = (By.CSS_SELECTOR, "input[name='zip']")
    ZIP_CODE_FIELD = (By.CSS_SELECTOR, "input[name='email']")
    EMAIL_FIELD = "input[name='email']"
    PAY_BUTTON = (By.CSS_SELECTOR, "button#paybtn.UiButton_container_2qlbE.FormSection_payBtn_2omG1")


